//! Linux host telemetry.
//!
//! Linux exposes kernel state through virtual filesystems instead of a
//! dedicated metrics API. `/proc` is generated by the kernel on read: it is
//! not ordinary data stored on disk. The agent samples cumulative CPU counters
//! from `/proc/stat`, reads memory availability from `/proc/meminfo`, and reads
//! monotonic boot uptime from `/proc/uptime`. Filesystem capacity comes from
//! `df`, which asks the kernel for the mounted root filesystem's `statfs`
//! values. Keeping these primitives here makes the Linux boundary explicit.

use super::*;

pub async fn stats() -> Result<NodeStats> {
    let first = cpu_sample().await;
    tokio::time::sleep(std::time::Duration::from_millis(500)).await;
    let second = cpu_sample().await;

    let cpu = if second.1 > first.1 {
        // `/proc/stat` counters are cumulative scheduler ticks. Comparing two
        // snapshots yields the share spent outside the idle counter.
        (1.0 - (second.0 - first.0) as f64 / (second.1 - first.1) as f64) * 100.0
    } else {
        0.0
    };
    let (memory_total, memory_available) = memory_stats().await;
    let (disk_total, disk_used) = disk_stats().await;

    Ok(NodeStats {
        cpu: cpu.clamp(0.0, 100.0),
        memory_used: (memory_total - memory_available).max(0),
        memory_total,
        disk_used,
        disk_total,
        uptime: uptime_seconds().await,
        cpus: std::thread::available_parallelism()
            .map(|value| value.get() as i32)
            .unwrap_or(1),
    })
}

async fn cpu_sample() -> (u64, u64) {
    let text = fs::read_to_string("/proc/stat").await.unwrap_or_default();
    let values: Vec<u64> = text
        .lines()
        .next()
        .unwrap_or("")
        .split_whitespace()
        .skip(1)
        .filter_map(|value| value.parse().ok())
        .collect();
    (values.get(3).copied().unwrap_or(0), values.iter().sum())
}

async fn memory_stats() -> (i64, i64) {
    let text = fs::read_to_string("/proc/meminfo")
        .await
        .unwrap_or_default();
    let mut total = 0;
    let mut available = 0;
    for line in text.lines() {
        if line.starts_with("MemTotal:") {
            total = parse_kb(line);
        } else if line.starts_with("MemAvailable:") {
            available = parse_kb(line);
        }
    }
    (total, available)
}

async fn uptime_seconds() -> i64 {
    fs::read_to_string("/proc/uptime")
        .await
        .ok()
        .and_then(|value| value.split_whitespace().next()?.parse::<f64>().ok())
        .unwrap_or(0.0) as i64
}

fn parse_kb(line: &str) -> i64 {
    line.split_whitespace()
        .nth(1)
        .and_then(|value| value.parse::<i64>().ok())
        .unwrap_or(0)
        * 1024
}

async fn disk_stats() -> (i64, i64) {
    let output = process::run("df", ["-B1", "--output=size,used", "/"])
        .await
        .unwrap_or_default();
    let values: Vec<i64> = output
        .lines()
        .last()
        .unwrap_or("")
        .split_whitespace()
        .filter_map(|value| value.parse().ok())
        .collect();
    (
        values.first().copied().unwrap_or(0),
        values.get(1).copied().unwrap_or(0),
    )
}
