//! Linux host telemetry.
//!
//! Linux exposes kernel state through virtual filesystems instead of a
//! dedicated metrics API. `/proc` is generated by the kernel on read: it is
//! not ordinary data stored on disk. The agent samples cumulative CPU counters
//! from `/proc/stat`, reads memory availability from `/proc/meminfo`, and reads
//! monotonic boot uptime from `/proc/uptime`. Filesystem capacity comes
//! directly from the root filesystem's `statvfs` values. Keeping these
//! primitives here makes the Linux boundary explicit.

use super::*;

pub async fn stats() -> Result<NodeStats> {
    let first = cpu_sample().await;
    tokio::time::sleep(std::time::Duration::from_millis(500)).await;
    let second = cpu_sample().await;

    let cpu = if second.1 > first.1 {
        // `/proc/stat` counters are cumulative scheduler ticks. Comparing two
        // snapshots yields the share spent outside the idle counter.
        (1.0 - (second.0 - first.0) as f64 / (second.1 - first.1) as f64) * 100.0
    } else {
        0.0
    };
    let (memory_total, memory_available) = memory_stats().await;
    let (disk_total, disk_used) = disk_stats().await;

    Ok(NodeStats {
        cpu: cpu.clamp(0.0, 100.0),
        memory_used: (memory_total - memory_available).max(0),
        memory_total,
        disk_used,
        disk_total,
        uptime: uptime_seconds().await,
        cpus: second.2.max(1),
    })
}

async fn cpu_sample() -> (u64, u64, i32) {
    let text = fs::read_to_string("/proc/stat").await.unwrap_or_default();
    let values: Vec<u64> = text
        .lines()
        .next()
        .unwrap_or("")
        .split_whitespace()
        .skip(1)
        .filter_map(|value| value.parse().ok())
        .collect();
    let cpus = text
        .lines()
        .filter(|line| line.as_bytes().get(3).is_some_and(u8::is_ascii_digit))
        .count() as i32;
    (
        values.get(3).copied().unwrap_or(0),
        values.iter().sum(),
        cpus,
    )
}

async fn memory_stats() -> (i64, i64) {
    let text = fs::read_to_string("/proc/meminfo")
        .await
        .unwrap_or_default();
    let mut total = 0;
    let mut available = 0;
    for line in text.lines() {
        if line.starts_with("MemTotal:") {
            total = parse_kb(line);
        } else if line.starts_with("MemAvailable:") {
            available = parse_kb(line);
        }
    }
    (total, available)
}

async fn uptime_seconds() -> i64 {
    fs::read_to_string("/proc/uptime")
        .await
        .ok()
        .and_then(|value| value.split_whitespace().next()?.parse::<f64>().ok())
        .unwrap_or(0.0) as i64
}

fn parse_kb(line: &str) -> i64 {
    line.split_whitespace()
        .nth(1)
        .and_then(|value| value.parse::<i64>().ok())
        .unwrap_or(0)
        * 1024
}

async fn disk_stats() -> (i64, i64) {
    #[cfg(unix)]
    {
        return tokio::task::spawn_blocking(root_filesystem_stats)
            .await
            .ok()
            .and_then(Result::ok)
            .unwrap_or_default();
    }

    #[cfg(not(unix))]
    (0, 0)
}

#[cfg(unix)]
fn root_filesystem_stats() -> std::io::Result<(i64, i64)> {
    let mut stats = std::mem::MaybeUninit::<libc::statvfs>::uninit();

    // SAFETY: the path is a static NUL-terminated string, and `stats` points
    // to writable storage for the exact structure expected by `statvfs`.
    if unsafe { libc::statvfs(c"/".as_ptr(), stats.as_mut_ptr()) } != 0 {
        return Err(std::io::Error::last_os_error());
    }

    // SAFETY: a successful `statvfs` call initializes the complete structure.
    let stats = unsafe { stats.assume_init() };
    let block_size = if stats.f_frsize > 0 {
        stats.f_frsize
    } else {
        stats.f_bsize
    } as u128;
    let total = (stats.f_blocks as u128).saturating_mul(block_size);
    let free = (stats.f_bfree as u128).saturating_mul(block_size);
    let used = total.saturating_sub(free);

    Ok((saturating_i64(total), saturating_i64(used)))
}

#[cfg(unix)]
fn saturating_i64(value: u128) -> i64 {
    value.min(i64::MAX as u128) as i64
}

#[cfg(all(test, unix))]
mod tests {
    use super::*;

    #[test]
    fn native_root_filesystem_stats_are_sane() {
        let (total, used) = root_filesystem_stats().expect("read root filesystem statistics");
        assert!(total > 0);
        assert!((0..=total).contains(&used));
    }
}
